### ISSUE TITLE
request rate of host & cluster only of half of the actual value

### ISSUE THREAD

**Issue by fywb0130** [Netflix/Turbine#125]
I use turbine to monitor a cluster of tow instance, the request rate of host & cluster in turbine dashboard just equal to the value in the hystirx dashboard of a single instance. It means that when I sum the value of two instance, the request rate of host & cluster in turbine dashboard is only half of the acture value.

![default](https://user-images.githubusercontent.com/1791815/35039730-624d8178-fb44-11e7-97cf-f4de029524b5.jpg)

the full context of aplication.yml:
```
management:
  security:
    enabled: false
spring:
  application:
    name: turbine
server:
  port: 9386
turbine:
  app-config: xxx
  cluster-name-expression: aSGName
  instanceUrlSuffix:
    xxx: xxx/hystrix.stream
  aggregator:
      cluster-config: xxx

eureka:
  client:
    service-url:
      defaultZone: http://eurekahost:9396/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
```
Any help will be welcome!
