### ISSUE TITLE
ConfigPropertyBasedDiscovery: support hostname with port

### ISSUE THREAD

**Issue by BarathArivazhagan** [Netflix/Turbine#127]
while building the list of instances for ConfigPropertyBasedDiscovery, is it possible to support port as part of hostname  instead of reading ports from attributes property of Instance? 

FROM

```
turbine:
  aggregator:
      clusterConfig: dev,test,prod
  instanceUrlSuffix: :9502/actuator/hystrix.stream
  ConfigPropertyBasedDiscovery:
    default: 
      instances: localhost 
```

To

```
turbine:
  aggregator:
      clusterConfig: dev,test,prod
  ConfigPropertyBasedDiscovery:
    default: 
      instances: localhost:9502,localhost:9503,localhost:9504
```

Tweaking below code might do the trick: 

```
   String[] parts = instanceList.split(",");

        List<Instance> instances = new ArrayList<Instance>();
        for (String s : parts) {
            instances.add(new Instance(s, cluster, true));
        }
```
or else provide the users on how to  set the port explicitly as part of property for ConfigPropertyBasedDiscovery rather than providing custom implementation of the discovery?
